{% set name = "nxmx" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nxmx-{{ version }}.tar.gz
  sha256: eb3310de9f74404c6b261cc213e5af1e4d7b148731111c17e89ab7695e551b81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - h5py
    - pint
    - python-dateutil
    - scipy
    - numpy <2.0

test:
  imports:
    - nxmx
  commands:
    - pip check
    - pytest tests
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://pypi.org/project/nxmx/
  summary: Read HDF5 data conforming to the NXmx application definition of the NeXus format
  license: BSD-3-Clause
  license_file: LICENCE

extra:
  recipe-maintainers:
    - ndevenish
    - jbeilstenedmands
    - rjgildea
