{% set name = "nxmx" %}
{% set version = "0.0.6" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nxmx-{{ version }}.tar.gz
  sha256: 9cf2504f6eae3629f1d8fe16e7c53303f61daf4616b32343292d18898fb8d526 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - h5py
    - pint
    - python-dateutil
    - scipy
    - numpy

test:
  imports:
    - nxmx
  commands:
    - pip check
    - pytest tests
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://pypi.org/project/nxmx/
  summary: Read HDF5 data conforming to the NXmx application definition of the NeXus format
  license: BSD-3-Clause
  license_file: LICENCE

extra:
  recipe-maintainers:
    - ndevenish
    - jbeilstenedmands
    - rjgildea
